-- CreateTable
CREATE TABLE "staging_conti" (
    "id" TEXT NOT NULL,
    "codice" TEXT,
    "codiceFiscaleAzienda" TEXT,
    "descrizione" TEXT,
    "descrizioneLocale" TEXT,
    "sigla" TEXT,
    "livello" TEXT,
    "tipo" TEXT,
    "gruppo" TEXT,
    "naturaConto" TEXT,
    "controlloSegno" TEXT,
    "validoImpresaOrdinaria" TEXT,
    "validoImpresaSemplificata" TEXT,
    "validoProfessionistaOrdinario" TEXT,
    "validoProfessionistaSemplificato" TEXT,
    "validoUnicoPf" TEXT,
    "validoUnicoSp" TEXT,
    "validoUnicoSc" TEXT,
    "validoUnicoEnc" TEXT,
    "codiceClasseIrpefIres" TEXT,
    "codiceClasseIrap" TEXT,
    "codiceClasseProfessionista" TEXT,
    "codiceClasseIrapProfessionista" TEXT,
    "codiceClasseIva" TEXT,
    "codiceClasseDatiStudiSettore" TEXT,
    "contoDareCee" TEXT,
    "contoAvereCee" TEXT,
    "contoCostiRicaviCollegato" TEXT,
    "gestioneBeniAmmortizzabili" TEXT,
    "percDeduzioneManutenzione" TEXT,
    "dettaglioClienteFornitore" TEXT,
    "numeroColonnaRegCronologico" TEXT,
    "numeroColonnaRegIncassiPag" TEXT,
    "descrizioneBilancioDare" TEXT,
    "descrizioneBilancioAvere" TEXT,
    "subcodiceAzienda" TEXT,
    "utilizzaDescrizioneLocale" TEXT,
    "consideraNelBilancioSemplificato" TEXT,
    "tabellaItalstudio" TEXT,
    "sourceFileName" TEXT,
    "importedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "staging_conti_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "staging_conti_codice_codiceFiscaleAzienda_key" ON "staging_conti"("codice", "codiceFiscaleAzienda");
