-- AlterTable
ALTER TABLE "Cliente" ADD COLUMN     "cap" TEXT,
ADD COLUMN     "codicePagamento" TEXT,
ADD COLUMN     "codiceValuta" TEXT,
ADD COLUMN     "cognome" TEXT,
ADD COLUMN     "comune" TEXT,
ADD COLUMN     "comuneNascita" TEXT,
ADD COLUMN     "dataNascita" TIMESTAMP(3),
ADD COLUMN     "indirizzo" TEXT,
ADD COLUMN     "nazione" TEXT,
ADD COLUMN     "nomeAnagrafico" TEXT,
ADD COLUMN     "provincia" TEXT,
ADD COLUMN     "sesso" TEXT,
ADD COLUMN     "telefono" TEXT,
ADD COLUMN     "tipoAnagrafica" TEXT;

-- AlterTable
ALTER TABLE "Fornitore" ADD COLUMN     "aliquota" DOUBLE PRECISION,
ADD COLUMN     "attivitaMensilizzazione" INTEGER,
ADD COLUMN     "cap" TEXT,
ADD COLUMN     "codicePagamento" TEXT,
ADD COLUMN     "codiceRitenuta" TEXT,
ADD COLUMN     "codiceValuta" TEXT,
ADD COLUMN     "cognome" TEXT,
ADD COLUMN     "comune" TEXT,
ADD COLUMN     "comuneNascita" TEXT,
ADD COLUMN     "contributoPrevidenziale" BOOLEAN,
ADD COLUMN     "contributoPrevidenzialeL335" TEXT,
ADD COLUMN     "dataNascita" TIMESTAMP(3),
ADD COLUMN     "enasarco" BOOLEAN,
ADD COLUMN     "gestione770" BOOLEAN,
ADD COLUMN     "indirizzo" TEXT,
ADD COLUMN     "nazione" TEXT,
ADD COLUMN     "nomeAnagrafico" TEXT,
ADD COLUMN     "percContributoCassaPrev" DOUBLE PRECISION,
ADD COLUMN     "provincia" TEXT,
ADD COLUMN     "quadro770" TEXT,
ADD COLUMN     "sesso" TEXT,
ADD COLUMN     "soggettoInail" BOOLEAN,
ADD COLUMN     "soggettoRitenuta" BOOLEAN,
ADD COLUMN     "telefono" TEXT,
ADD COLUMN     "tipoAnagrafica" TEXT,
ADD COLUMN     "tipoRitenuta" TEXT;
