-- AlterTable
ALTER TABLE "staging_righe_contabili" ADD COLUMN     "contoDaRilevareMovimento1" TEXT,
ADD COLUMN     "contoDaRilevareMovimento2" TEXT,
ADD COLUMN     "dettaglioCliForCodiceFiscale" TEXT,
ADD COLUMN     "dettaglioCliForSigla" TEXT,
ADD COLUMN     "dettaglioCliForSubcodice" TEXT,
ADD COLUMN     "esercizioDiRilevanzaFiscale" TEXT,
ADD COLUMN     "insDatiMovimentiAnalitici" TEXT,
ADD COLUMN     "insDatiStudiDiSettore" TEXT,
ADD COLUMN     "noteDiCompetenza" TEXT,
ADD COLUMN     "siglaConto" TEXT,
ADD COLUMN     "statoMovimentoStudi" TEXT;

-- AlterTable
ALTER TABLE "staging_righe_iva" ADD COLUMN     "imponibile50CorrNonCons" TEXT,
ADD COLUMN     "impostaIntrattenimenti" TEXT;

-- AlterTable
ALTER TABLE "staging_testate" ADD COLUMN     "cliForCodiceFiscalePartita" TEXT,
ADD COLUMN     "cliForIntraCodiceFiscale" TEXT,
ADD COLUMN     "cliForIntraSigla" TEXT,
ADD COLUMN     "cliForIntraSubcodice" TEXT,
ADD COLUMN     "cliForSiglaPartita" TEXT,
ADD COLUMN     "cliForSubcodicePartita" TEXT,
ADD COLUMN     "clienteFornitoreSubcodice" TEXT,
ADD COLUMN     "codiceAttivita" TEXT,
ADD COLUMN     "codiceAttivitaIvaPartita" TEXT,
ADD COLUMN     "codiceNumerazioneIva" TEXT,
ADD COLUMN     "codiceNumerazioneIvaPartita" TEXT,
ADD COLUMN     "codiceNumerazioneIvaVendite" TEXT,
ADD COLUMN     "codicePagamento" TEXT,
ADD COLUMN     "codiceValuta" TEXT,
ADD COLUMN     "documentoBis" TEXT,
ADD COLUMN     "documentoBisPartita" TEXT,
ADD COLUMN     "documentoDataPartita" TEXT,
ADD COLUMN     "documentoNumeroPartita" TEXT,
ADD COLUMN     "documentoOperazione" TEXT,
ADD COLUMN     "enasarco" TEXT,
ADD COLUMN     "protocolloBis" TEXT,
ADD COLUMN     "protocolloBisAutofattura" TEXT,
ADD COLUMN     "protocolloNumeroAutofattura" TEXT,
ADD COLUMN     "stato" TEXT,
ADD COLUMN     "subcodiceAzienda" TEXT,
ADD COLUMN     "tipoGestionePartite" TEXT,
ADD COLUMN     "tipoMovimentoIntrastat" TEXT,
ADD COLUMN     "tipoRegistroIvaPartita" TEXT,
ADD COLUMN     "totaleInValuta" TEXT,
ADD COLUMN     "versamentoData" TEXT,
ADD COLUMN     "versamentoEstremi" TEXT,
ADD COLUMN     "versamentoModello" TEXT,
ADD COLUMN     "versamentoTipo" TEXT;
