import { FieldDefinition } from '../../../lib/fixedWidthParser';

export const pnTestaDefinitions: FieldDefinition[] = [
  { fieldName: 'codiceFiscaleAzienda', length: 16, start: 4, end: 19 },
  { fieldName: 'subcodiceFiscaleAzienda', length: 1, start: 20, end: 20 },
  { fieldName: 'externalId', length: 12, start: 21, end: 32, isKey: true },
  { fieldName: 'codiceAttivita', length: 2, start: 33, end: 34 },
  { fieldName: 'esercizio', length: 5, start: 35, end: 39 },
  { fieldName: 'causaleId', length: 6, start: 40, end: 45 },
  { fieldName: 'descrizioneCausale', length: 40, start: 46, end: 85 },
  { fieldName: 'dataRegistrazione', length: 8, start: 86, end: 93, type: 'string' },
  { fieldName: 'codiceAttivitaIva', length: 2, start: 94, end: 95 },
  { fieldName: 'tipoRegistroIva', length: 1, start: 96, end: 96 },
  { fieldName: 'codiceNumerazioneIva', length: 3, start: 97, end: 99 },
  { fieldName: 'clienteFornitoreCodiceFiscale', length: 16, start: 100, end: 115 },
  { fieldName: 'clienteFornitoreSubcodice', length: 1, start: 116, end: 116 },
  { fieldName: 'clienteFornitoreSigla', length: 12, start: 117, end: 128 },
  { fieldName: 'dataDocumento', length: 8, start: 129, end: 136, type: 'string' },
  { fieldName: 'numeroDocumento', length: 12, start: 137, end: 148 },
  { fieldName: 'documentoBis', length: 1, start: 149, end: 149 },
  { fieldName: 'dataRegistroIva', length: 8, start: 150, end: 157, type: 'string' },
  { fieldName: 'protocolloNumero', length: 6, start: 158, end: 163 },
  { fieldName: 'protocolloBis', length: 1, start: 164, end: 164 },
  { fieldName: 'dataCompetenzaLiquidIva', length: 8, start: 165, end: 172, type: 'string' },
  { fieldName: 'totaleDocumento', length: 12, start: 173, end: 184, type: 'string' },
  { fieldName: 'dataCompetenzaContabile', length: 8, start: 185, end: 192, type: 'string' },
  { fieldName: 'noteMovimento', length: 60, start: 193, end: 252 },
  { fieldName: 'dataPlafond', length: 8, start: 253, end: 260, type: 'string' },
  { fieldName: 'annoProRata', length: 4, start: 261, end: 264, type: 'string' },
  { fieldName: 'ritenute', length: 12, start: 265, end: 276, type: 'string' },
  { fieldName: 'enasarco', length: 12, start: 277, end: 288, type: 'string' },
  { fieldName: 'totaleInValuta', length: 12, start: 289, end: 300, type: 'string' },
  { fieldName: 'codiceValuta', length: 4, start: 301, end: 304 },
  { fieldName: 'codiceNumerazioneIvaVendite', length: 3, start: 305, end: 307 },
  { fieldName: 'protocolloNumeroAutofattura', length: 6, start: 308, end: 313 },
  { fieldName: 'protocolloBisAutofattura', length: 1, start: 314, end: 314 },
  { fieldName: 'versamentoData', length: 8, start: 315, end: 322, type: 'string' },
  { fieldName: 'versamentoTipo', length: 1, start: 323, end: 323 },
  { fieldName: 'versamentoModulo', length: 1, start: 324, end: 324 },
  { fieldName: 'versamentoEstremi', length: 16, start: 325, end: 340 },
  { fieldName: 'stato', length: 1, start: 341, end: 341 },
  { fieldName: 'tipoGestionePartite', length: 1, start: 342, end: 342 },
  { fieldName: 'codicePagamento', length: 8, start: 343, end: 350 },
  { fieldName: 'codiceAttivitaIvaPartita', length: 2, start: 351, end: 352 },
  { fieldName: 'tipoRegistroIvaPartita', length: 1, start: 353, end: 353 },
  { fieldName: 'codiceNumerazioneIvaPartita', length: 3, start: 354, end: 356 },
  { fieldName: 'cliForCodiceFiscalePartita', length: 16, start: 357, end: 372 },
  { fieldName: 'cliForSubcodicePartita', length: 1, start: 373, end: 373 },
  { fieldName: 'cliForSiglaPartita', length: 12, start: 374, end: 385 },
  { fieldName: 'documentoDataPartita', length: 8, start: 386, end: 393, type: 'string' },
  { fieldName: 'documentoNumeroPartita', length: 12, start: 394, end: 405 },
  { fieldName: 'documentoBisPartita', length: 1, start: 406, end: 406 },
  { fieldName: 'cliForIntraCodiceFiscale', length: 16, start: 407, end: 422 },
  { fieldName: 'cliForIntraSubcodice', length: 1, start: 423, end: 423 },
  { fieldName: 'cliForIntraSigla', length: 12, start: 424, end: 435 },
  { fieldName: 'tipoMovimentoIntrastat', length: 2, start: 436, end: 437 },
  { fieldName: 'documentoOperazione', length: 8, start: 438, end: 445, type: 'string' },
];

export const pnRigConDefinitions: FieldDefinition[] = [
  { fieldName: 'externalId', length: 12, start: 4, end: 15, isKey: true },
  { fieldName: 'progressivoRigo', length: 3, start: 16, end: 18, isKey: true, type: 'string' },
  { fieldName: 'tipoConto', length: 1, start: 19, end: 19 },
  { fieldName: 'clienteFornitoreCodiceFiscale', length: 16, start: 20, end: 35 },
  { fieldName: 'clienteFornitoreSubcodice', length: 1, start: 36, end: 36 },
  { fieldName: 'clienteFornitoreSigla', length: 12, start: 37, end: 48 },
  { fieldName: 'conto', length: 10, start: 49, end: 58 },
  { fieldName: 'importoDare', length: 12, start: 59, end: 70, type: 'string' },
  { fieldName: 'importoAvere', length: 12, start: 71, end: 82, type: 'string' },
  { fieldName: 'note', length: 60, start: 83, end: 142 },
  { fieldName: 'insDatiCompetenzaContabile', length: 1, start: 143, end: 143 },
  { fieldName: 'dataInizioCompetenza', length: 8, start: 144, end: 151, type: 'string' },
  { fieldName: 'dataFineCompetenza', length: 8, start: 152, end: 159, type: 'string' },
  { fieldName: 'noteDiCompetenza', length: 60, start: 160, end: 219 },
  { fieldName: 'dataRegistrazioneApertura', length: 8, start: 220, end: 227, type: 'string' },
  { fieldName: 'contoDaRilevareMovimento1', length: 10, start: 228, end: 237 },
  { fieldName: 'contoDaRilevareMovimento2', length: 10, start: 238, end: 247 },
  { fieldName: 'insDatiMovimentiAnalitici', length: 1, start: 248, end: 248, type: 'string' },
  { fieldName: 'dataInizioCompetenzaAnalit', length: 8, start: 249, end: 256, type: 'string' },
  { fieldName: 'dataFineCompetenzaAnalit', length: 8, start: 257, end: 264, type: 'string' },
  { fieldName: 'insDatiStudiDiSettore', length: 1, start: 265, end: 265 },
  { fieldName: 'statoMovimentoStudi', length: 1, start: 266, end: 266 },
  { fieldName: 'esercizioDiRilevanzaFiscale', length: 5, start: 267, end: 271 },
  { fieldName: 'dettaglioCliForCodiceFiscale', length: 16, start: 272, end: 287 },
  { fieldName: 'dettaglioCliForSubcodice', length: 1, start: 288, end: 288 },
  { fieldName: 'dettaglioCliForSigla', length: 12, start: 289, end: 300 },
  { fieldName: 'siglaConto', length: 12, start: 301, end: 312 },
];

// DEFINIZIONE CORRETTA PER TRACCIATO PNRIGIVA VECCHIO (senza siglaContropartita)
export const pnRigIvaVecchioDefinitions: FieldDefinition[] = [
  { fieldName: 'externalId', length: 12, start: 4, end: 15, isKey: true },
  { fieldName: 'codiceIva', length: 4, start: 16, end: 19 },
  { fieldName: 'contropartita', length: 10, start: 20, end: 29 },
  { fieldName: 'imponibile', length: 12, start: 30, end: 41, type: 'string' },
  { fieldName: 'imposta', length: 12, start: 42, end: 53, type: 'string' },
  { fieldName: 'impostaIntrattenimenti', length: 12, start: 54, end: 65, type: 'string' },
  { fieldName: 'imponibile50CorrNonCons', length: 12, start: 66, end: 77, type: 'string' },
  { fieldName: 'impostaNonConsiderata', length: 12, start: 78, end: 89, type: 'string' },
  { fieldName: 'importoLordo', length: 12, start: 90, end: 101, type: 'string' },
  { fieldName: 'note', length: 60, start: 102, end: 161 },
];

// DEFINIZIONE CORRETTA PER TRACCIATO PNRIGIVA NUOVO/ESTESO
export const pnRigIvaNuovoDefinitions: FieldDefinition[] = [
  ...pnRigIvaVecchioDefinitions,
  { fieldName: 'siglaContropartita', length: 12, start: 162, end: 173 },
];

export const movAnacDefinitions: FieldDefinition[] = [
  { fieldName: 'externalId', length: 12, start: 4, end: 15, isKey: true },
  { fieldName: 'progressivoRigoContabile', length: 3, start: 16, end: 18, isKey: true, type: 'string' },
  { fieldName: 'centroDiCosto', length: 4, start: 19, end: 22 },
  { fieldName: 'parametro', length: 12, start: 23, end: 34, type: 'string' },
];