"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.movAnacDefinitions = exports.pnRigIvaDefinitions = exports.pnRigConDefinitions = exports.pnTestaDefinitions = void 0;
exports.pnTestaDefinitions = [
    { fieldName: 'FILLER', length: 3, start: 1, end: 3 },
    { fieldName: 'CODICE_FISCALE_AZIENDA', length: 16, start: 4, end: 19 },
    { fieldName: 'SUBCODICE_FISCALE_AZIENDA', length: 1, start: 20, end: 20 },
    { fieldName: 'CODICE_UNIVOCO_SCARICAMENTO', length: 12, start: 21, end: 32, isKey: true },
    { fieldName: 'CODICE_ATTIVITA', length: 2, start: 33, end: 34 },
    { fieldName: 'ESERCIZIO', length: 5, start: 35, end: 39 },
    { fieldName: 'CODICE_CAUSALE', length: 6, start: 40, end: 45 },
    { fieldName: 'DESCRIZIONE_CAUSALE', length: 40, start: 46, end: 85 },
    { fieldName: 'DATA_REGISTRAZIONE', length: 8, start: 86, end: 93 },
    { fieldName: 'CODICE_ATTIVITA_IVA', length: 2, start: 94, end: 95 },
    { fieldName: 'TIPO_REGISTRO_IVA', length: 1, start: 96, end: 96 },
    { fieldName: 'CODICE_NUMERAZIONE_IVA', length: 3, start: 97, end: 99 },
    { fieldName: 'CLIENTE_FORNITORE_CODICE_FISCALE', length: 16, start: 100, end: 115 },
    { fieldName: 'CLIENTE_FORNITORE_SUBCODICE', length: 1, start: 116, end: 116 },
    { fieldName: 'CLIENTE_FORNITORE_SIGLA', length: 12, start: 117, end: 128 },
    { fieldName: 'DOCUMENTO_DATA', length: 8, start: 129, end: 136 },
    { fieldName: 'DOCUMENTO_NUMERO', length: 12, start: 137, end: 148 },
    { fieldName: 'DOCUMENTO_BIS', length: 1, start: 149, end: 149 },
    { fieldName: 'DATA_REGISTRO_IVA', length: 8, start: 150, end: 157 },
    { fieldName: 'PROTOCOLLO_NUMERO', length: 6, start: 158, end: 163 },
    { fieldName: 'PROTOCOLLO_BIS', length: 1, start: 164, end: 164 },
    { fieldName: 'DATA_COMPETENZA_LIQUID_IVA', length: 8, start: 165, end: 172 },
    { fieldName: 'TOTALE_DOCUMENTO', length: 12, start: 173, end: 184 },
    { fieldName: 'DATA_COMPETENZA_CONTABILE', length: 8, start: 185, end: 192 },
    { fieldName: 'NOTE_MOVIMENTO', length: 60, start: 193, end: 252 },
    { fieldName: 'DATA_PLAFOND', length: 8, start: 253, end: 260 },
    { fieldName: 'ANNO_PRO_RATA', length: 4, start: 261, end: 264 },
    { fieldName: 'RITENUTE', length: 12, start: 265, end: 276 },
    { fieldName: 'ENASARCO', length: 12, start: 277, end: 288 },
    { fieldName: 'TOTALE_IN_VALUTA', length: 12, start: 289, end: 300 },
    { fieldName: 'CODICE_VALUTA', length: 4, start: 301, end: 304 },
    { fieldName: 'CODICE_NUMERAZIONE_IVA_VENDITE', length: 3, start: 305, end: 307 },
    { fieldName: 'PROTOCOLLO_NUMERO_AUTOFATTURA', length: 6, start: 308, end: 313 },
    { fieldName: 'PROTOCOLLO_BIS_AUTOFATTURA', length: 1, start: 314, end: 314 },
    { fieldName: 'VERSAMENTO_DATA', length: 8, start: 315, end: 322 },
    { fieldName: 'VERSAMENTO_TIPO', length: 1, start: 323, end: 323 },
    { fieldName: 'VERSAMENTO_MODULO', length: 1, start: 324, end: 324 },
    { fieldName: 'VERSAMENTO_ESTREMI', length: 16, start: 325, end: 340 },
    { fieldName: 'STATO', length: 1, start: 341, end: 341 },
    { fieldName: 'TIPO_GESTIONE_PARTITE', length: 1, start: 342, end: 342 },
    { fieldName: 'CODICE_PAGAMENTO', length: 8, start: 343, end: 350 },
    { fieldName: 'CODICE_ATTIVITA_IVA_PARTITA', length: 2, start: 351, end: 352 },
    { fieldName: 'TIPO_REGISTRO_IVA_PARTITA', length: 1, start: 353, end: 353 },
    { fieldName: 'CODICE_NUMERAZIONE_IVA_PARTITA', length: 3, start: 354, end: 356 },
    { fieldName: 'CLI_FOR_CODICE_FISCALE_PARTITA', length: 16, start: 357, end: 372 },
    { fieldName: 'CLI_FOR_SUBCODICE_PARTITA', length: 1, start: 373, end: 373 },
    { fieldName: 'CLI_FOR_SIGLA_PARTITA', length: 12, start: 374, end: 385 },
    { fieldName: 'DOCUMENTO_DATA_PARTITA', length: 8, start: 386, end: 393 },
    { fieldName: 'DOCUMENTO_NUMERO_PARTITA', length: 12, start: 394, end: 405 },
    { fieldName: 'DOCUMENTO_BIS_PARTITA', length: 1, start: 406, end: 406 },
    { fieldName: 'CLI_FOR_INTRA_CODICE_FISCALE', length: 16, start: 407, end: 422 },
    { fieldName: 'CLI_FOR_INTRA_SUBCODICE', length: 1, start: 423, end: 423 },
    { fieldName: 'CLI_FOR_INTRA_SIGLA', length: 12, start: 424, end: 435 },
    { fieldName: 'TIPO_MOVIMENTO_INTRASTAT', length: 2, start: 436, end: 437 },
    { fieldName: 'DOCUMENTO_OPERAZIONE', length: 8, start: 438, end: 445 },
];
exports.pnRigConDefinitions = [
    { fieldName: 'FILLER', length: 3, start: 1, end: 3 },
    { fieldName: 'CODICE_UNIVOCO_SCARICAMENTO', length: 12, start: 4, end: 15, isKey: true },
    { fieldName: 'PROGRESSIVO_NUMERO_RIGO', length: 3, start: 16, end: 18, isKey: true },
    { fieldName: 'TIPO_CONTO', length: 1, start: 19, end: 19 },
    { fieldName: 'CLIENTE_FORNITORE_CODICE_FISCALE', length: 16, start: 20, end: 35 },
    { fieldName: 'CLIENTE_FORNITORE_SUBCODICE', length: 1, start: 36, end: 36 },
    { fieldName: 'CLIENTE_FORNITORE_SIGLA', length: 12, start: 37, end: 48 },
    { fieldName: 'CONTO', length: 10, start: 49, end: 58 },
    { fieldName: 'IMPORTO_DARE', length: 12, start: 59, end: 70 },
    { fieldName: 'IMPORTO_AVERE', length: 12, start: 71, end: 82 },
    { fieldName: 'NOTE', length: 60, start: 83, end: 142 },
    { fieldName: 'INS_DATI_COMPETENZA_CONTABILE', length: 1, start: 143, end: 143 },
    { fieldName: 'DATA_INIZIO_COMPETENZA', length: 8, start: 144, end: 151 },
    { fieldName: 'DATA_FINE_COMPETENZA', length: 8, start: 152, end: 159 },
    { fieldName: 'NOTE_DI_COMPETENZA', length: 60, start: 160, end: 219 },
    { fieldName: 'DATA_REGISTRAZIONE_APERTURA', length: 8, start: 220, end: 227 },
    { fieldName: 'CONTO_DA_RILEVARE_MOVIMENTO_1', length: 10, start: 228, end: 237 },
    { fieldName: 'CONTO_DA_RILEVARE_MOVIMENTO_2', length: 10, start: 238, end: 247 },
    { fieldName: 'INS_DATI_MOVIMENTI_ANALITICI', length: 1, start: 248, end: 248 },
    { fieldName: 'DATA_INIZIO_COMPETENZA_ANALIT', length: 8, start: 249, end: 256 },
    { fieldName: 'DATA_FINE_COMPETENZA_ANALIT', length: 8, start: 257, end: 264 },
    { fieldName: 'INS_DATI_STUDI_DI_SETTORE', length: 1, start: 265, end: 265 },
    { fieldName: 'STATO_MOVIMENTO_STUDI', length: 1, start: 266, end: 266 },
    { fieldName: 'ESERCIZIO_DI_RILEVANZA_FISCALE', length: 5, start: 267, end: 271 },
    { fieldName: 'DETTAGLIO_CLI_FOR_CODICE_FISCALE', length: 16, start: 272, end: 287 },
    { fieldName: 'DETTAGLIO_CLI_FOR_SUBCODICE', length: 1, start: 288, end: 288 },
    { fieldName: 'DETTAGLIO_CLI_FOR_SIGLA', length: 12, start: 289, end: 300 },
    { fieldName: 'SIGLA_CONTO', length: 12, start: 301, end: 312 },
];
exports.pnRigIvaDefinitions = [
    { fieldName: 'FILLER', length: 3, start: 1, end: 3 },
    { fieldName: 'CODICE_UNIVOCO_SCARICAMENTO', length: 12, start: 4, end: 15, isKey: true },
    { fieldName: 'CODICE_IVA', length: 4, start: 16, end: 19 },
    { fieldName: 'CONTROPARTITA', length: 10, start: 20, end: 29 },
    { fieldName: 'IMPONIBILE', length: 12, start: 30, end: 41 },
    { fieldName: 'IMPOSTA', length: 12, start: 42, end: 53 },
    { fieldName: 'IMPOSTA_INTRATTENIMENTI', length: 12, start: 54, end: 65 },
    { fieldName: 'IMPONIBILE_50_CORR_NON_CONS', length: 12, start: 66, end: 77 },
    { fieldName: 'IMPOSTA_NON_CONSIDERATA', length: 12, start: 78, end: 89 },
    { fieldName: 'IMPORTO_LORDO', length: 12, start: 90, end: 101 },
    { fieldName: 'NOTE', length: 60, start: 102, end: 161 },
    { fieldName: 'SIGLA_CONTROPARTITA', length: 12, start: 162, end: 173 },
];
exports.movAnacDefinitions = [
    { fieldName: 'FILLER', length: 3, start: 1, end: 3 },
    { fieldName: 'CODICE_UNIVOCO_SCARICAMENTO', length: 12, start: 4, end: 15, isKey: true },
    { fieldName: 'PROGRESSIVO_NUMERO_RIGO_CONT', length: 3, start: 16, end: 18, isKey: true },
    { fieldName: 'CENTRO_DI_COSTO', length: 4, start: 19, end: 22 },
    { fieldName: 'PARAMETRO', length: 12, start: 23, end: 34 },
];
